#ifndef __BEASY_GTKPREF_NOTIFY_H
#define	__BEASY_GTKPREF_NOTIFY_H

#include "gtkprefs.h"

#define BEASY_PREFS_NTF_ROOT 					BEASY_PREFS_ROOT "/notify"

#define BEASY_PREFS_NTF_BEHAVIOR_ROOT 			BEASY_PREFS_NTF_ROOT "/behavior"
#define BEASY_PREFS_NTF_BEHAVIOR_DISPLAY_TIME 	BEASY_PREFS_NTF_BEHAVIOR_ROOT "/display_time"
#define BEASY_PREFS_NTF_BEHAVIOR_THROTTLE 		BEASY_PREFS_NTF_BEHAVIOR_ROOT "/throttle"

#define BEASY_PREFS_NTF_APPEARANCE_ROOT 		BEASY_PREFS_NTF_ROOT "/appearance"
#define BEASY_PREFS_NTF_APPEARANCE_POSITION 	BEASY_PREFS_NTF_APPEARANCE_ROOT "/position"
#define BEASY_PREFS_NTF_APPEARANCE_VERTICAL 	BEASY_PREFS_NTF_APPEARANCE_ROOT "/vertical"
#define BEASY_PREFS_NTF_APPEARANCE_ANIMATE 		BEASY_PREFS_NTF_APPEARANCE_ROOT "/animate"

#define BEASY_PREFS_NTF_MOUSE_ROOT 				BEASY_PREFS_NTF_ROOT "/mouse"
#define BEASY_PREFS_NTF_MOUSE_LEFT 				BEASY_PREFS_NTF_MOUSE_ROOT "/left"
#define BEASY_PREFS_NTF_MOUSE_RIGHT 			BEASY_PREFS_NTF_MOUSE_ROOT "/right"

#define BEASY_PREFS_NTF_LOADED_THEMES 			BEASY_PREFS_NTF_ROOT "/themes"
#define BEASY_PREFS_NTF_NOTIFICATIONS 			BEASY_PREFS_NTF_ROOT "/notifications"

#define BEASY_PREFS_NTF_ADVANCED_ROOT 			BEASY_PREFS_NTF_ROOT "/advanced"

#if GTK_CHECK_VERSION(2,2,0)
#define BEASY_PREFS_NTF_ADVANCED_SCREEN 		BEASY_PREFS_NTF_ADVANCED_ROOT "/screen"
#define BEASY_PREFS_NTF_ADVANCED_MONITOR 		BEASY_PREFS_NTF_ADVANCED_ROOT "/monitor"
#endif /* GTK_CHECK_VERSION(2,2,0) */

G_BEGIN_DECLS

GtkWidget *		beasy_notify_prefpage_get(void);


G_END_DECLS

#endif

